public class Constants {
    
    public static final String STATUS_COMPLETE = 'Complete';
    public static final String STATUS_INCOMPLETE = 'Incomplete';
        
    public static final String IMAGE = 'iVBORw0KGgoAAAANSUhEUgAAAAEAAAABCAIAAACQd1PeAAAACXBIWXMAAA7EAAAOxAGVKw4bAAAA' +
                                         'DElEQVQImWNITU0FAAJiATCoYcVSAAAAAElFTkSuQmCC';
    
    public static final String Image_2 = 'iVBORw0KGgoAAAANSUhEUgAAAAEAAAABCAIAAACQd1PeAAAAAXNSR0IArs4c6QAAAARnQU1BAACx' +
											'jwv8YQUAAAAJcEhZcwAADsMAAA7DAcdvqGQAAAAMSURBVBhXY/j//z8ABf4C/qc1gYQAAAAASUVORK5CYII=';
    
    public static final String LIST_OF_CARDS_PAGE = 'https://c.eu9.visual.force.com/apex/CardsListPage';
    public static final String NEW_CARD_PAGE = 'https://c.eu9.visual.force.com/apex/NewCardPage';
    
    public static final String ACCOUNT;
    public static final String CONTACT;
    
    public static final String SOBJECT_NAME = 'Name';
        
}